name: Build & Run Fish Detector

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t fish-detector .

      - name: Run container
        run: |
          mkdir -p output
          docker run --rm -v "${{ github.workspace }}/output:/app/output" fish-detector

      - name: List output files
        run: |
          ls -l output/
